[platformio]
default_envs = d1_mini

[env]
platform = espressif8266
framework = arduino
monitor_speed = 9600
build_flags =
  -Wall
  -Wextra
  -DPERRYN_FW_NAME=\"PerryNet\"
  -DPERRYN_DEFAULT_RTSCTS=0

[env:d1_mini]
board = d1_mini
upload_speed = 921600
build_flags =
  ${env.build_flags}
  -DPERRYN_HAS_RTSCTS=1

[env:esp12f]
board = esp12e
upload_speed = 115200
build_flags =
  ${env.build_flags}
  -DPERRYN_HAS_RTSCTS=1

[env:esp12s]
board = esp12e
upload_speed = 115200
build_flags =
  ${env.build_flags}
  -DPERRYN_HAS_RTSCTS=1

[env:esp01_1m]
board = esp01_1m
upload_speed = 115200
build_flags =
  ${env.build_flags}
  -DPERRYN_HAS_RTSCTS=0

[env:esp01]
board = esp01
upload_speed = 115200
build_flags =
  ${env.build_flags}
  -DPERRYN_HAS_RTSCTS=0
