[platformio]
default_envs = d1_mini

[env:d1_mini]
platform = espressif8266
board = d1_mini
framework = arduino
monitor_speed = 9600
upload_speed = 921600
build_flags =
  -Wall
  -Wextra
  -DPERRYN_FW_NAME=\"PerryNet\"
  -DPERRYN_DEFAULT_RTSCTS=0
